version: "3.4"
services:
  gremlin-server:
    container_name: gremlin-server
    image: tinkerpop/gremlin-server
    ports:
      - "8182:8182"
  integration-tests:
    container_name: integration-tests
    image: golang:1.17
    volumes:
      - .:/go_app
    environment:
      - GREMLIN_SERVER_HOSTNAME=gremlin-server
      - GREMLIN_SERVER_PORT=8182
      - RUN_INTEGRATION_TESTS=true
    working_dir: /go_app
    command:
      [
        "go",
        "test",
        "-v",
        "./...",
        "-race",
        "-covermode=atomic",
        "-coverprofile=\"coverage.out\""
      ]
    depends_on:
      - gremlin-server