name: build-test
on: [push, pull_request]
jobs:
  smoke:
    name: smoke
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install -DskipTests -Dci --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  go:
    name: Go
    timeout-minutes: 20
    needs: smoke
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Execute Go tests
        working-directory: ./gremlin-go
        run: |
          docker-compose up --exit-code-from gremlin-go-integration-tests gremlin-go-integration-tests
          docker-compose down

      # Note exit code is intentionally ignored here because not all these tests pass right now.
      - name: Execute Godog tests
        working-directory: ./gremlin-go
        run: |
          docker-compose up gremlin-go-godog-tests
          docker-compose down

      - name: Go-Vet
        working-directory: ./gremlin-go
        run: go vet ./...

      - name: Go-StaticCheck
        uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: "2021.1.1"
          install-go: false
          cache-key: ${{ matrix.go }}

      - name: Generate Cucumber Godog Test File
        working-directory: .
        run: |
          mvn install -pl :gremlin-core -DskipTests -DskipIntegrationTests=true
          mvn install -pl :gremlin-server -DskipTests -DskipIntegrationTests=true
          mvn compile -pl :gremlin-go
